server:
  port: 80
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
zuul:
  sensitive-headers:
  routes:
    test1:
      path: /test1
      url: http://localhost:3333

custom:
  auth:
    token: 123asdzxc
  router:
    type: ${ROUTER_TYPE:etcd}


